// actions/filter.js
export const CHANGE_DATE = 'CHANGE_DATE';
export const ADD_FILTER = 'ADD_FILTER';
export const SET_FILTERS = 'SET_FILTERS';
export const REMOVE_FILTER = 'REMOVE_FILTER';

// actions/index.js
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SLUG = 'FETCH_MOVIES_SLUG';
export const FETCH_ACTOR = 'FETCH_ACTOR';
export const FETCH_ACTOR_SLUG = 'FETCH_ACTOR_SLUG';
export const FETCH_ACTOR__SUCCESS = 'FETCH_ACTOR__SUCCESS';
export const FETCH_ACTOR_SLUG_SUCCESS = 'FETCH_ACTOR_SLUG_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const FETCH_FAIL_SLUG = 'FETCH_FAIL_SLUG';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_SLUG_SUCCESS = 'FETCH_MOVIES_SLUG_SUCCESS';
export const FETCH_CAROUSEL_MOVIES_SUCCESS = 'FETCH_CAROUSEL_MOVIES_SUCCESS';
export const FETCH_SCHEDULE_MOVIES_SUCCESS = 'FETCH_SCHEDULE_MOVIES_SUCCESS';
export const EDITING_MOVIE_SUCCESS = 'EDITING_MOVIE_SUCCESS';
export const EDITING_FAIL = 'EDITING_FAIL';
export const EDITING_ACTOR_SUCCESS = 'EDITING_ACTOR_SUCCESS';

// action/login.js
export const AUTH_START = 'AUTH_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SET_USER = 'SET_USER';
export const ADDITTIONAL_INFO = 'ADDITTIONAL_INFO';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
